name:  CI/CD

on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      -  main

jobs:
  build_deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install dependencies
        run: yarn install 
      - name: deploy to aws 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
          AWS_DEFAULT_OUTPUT: json
        run: npm run deploy