name:  CI/CD

on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      -  main

jobs:
  build_deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install 
      - name: Run deploy.sh 
        run: |
        unset AWS_SESSION_TOKEN
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SECRET_KEY
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Deploy to aws 
        run: npm run deploy