name:  CI/CD

on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      -  main

jobs:
  build_deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install dependencies
        run: yarn install
      # - name: test
      #   run: npm run test     
      - name: aws deploy
        run: npm run deploy