name:  CI/CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      -  master

  # pull_request:
  #   branches:
  #     - master

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn run build
      # - name: test
      #   run: npm run test

      # should save this keys in github, settings of the project, secrets :
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      # - name: aws deploy
        # run: BUILD_DIRECTORY=build BUCKET_NAME=yourBucketName AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy-aws